const ActionType = {
  ADD_CART: 'ADD_CART',
  INCREMENT_CART: 'INCREMENT_CART',
  DECREMENT_CART: 'DECREMENT_CART',
  DELETE_CART: 'DELETE_CART',
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_ERROR: 'ALERT_ERROR',
  ALERT_CLOSE: 'ALERT_CLOSE',
  MODAL_EDIT: 'MODAL_EDIT',
  MODAL_ADD: 'MODAL_ADD',
  MODAL_DELETE: 'MODAL_DELETE',
  MODAL_CLOSE: 'MODAL_CLOSE',
}
export default ActionType
